version: '3'
services:
  gm-user-service:
    build: ./user-service
    container_name: gm-user-service
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=dev  
    networks:
      - mynet
  gm-api-gateway:
    container_name: gm-api-gateway
    build: './api-gateway'
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=dev  
    links:
      - gm-user-service
    networks:
      - mynet    
networks:
  mynet:
    driver: bridge
    ipam:
      driver: default        
    
  
